#! /bin/bash

case "$1" in
	start)
		echo "Startng the simple server"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket
		;;
	stop)
		echo "Stopping the simple server"
		start-stop-daemon -K --signal TERM -n aesdsocket
		;;
	exit 1
esac
exit 0 

